#!/usr/bin/env bash
# Scans photos/ for new images, moves them into photos/journey/, converts
# HEIC → JPG, reads real EXIF creation dates, and writes
# photos/journey-manifest.js sorted chronologically.
#
# Usage:  ./scan-photos.sh
#
# Re-run any time you add or remove photos.

set -e

cd "$(dirname "$0")"

PHOTOS_DIR="photos"
JOURNEY_DIR="photos/journey"
OUT="photos/journey-manifest.js"

mkdir -p "$JOURNEY_DIR"

# 1. Pull any images sitting at the top level of photos/ into journey/.
#    (Files already inside journey/ stay put. README.md and journey-manifest.js are left alone.)
moved=0
for f in "$PHOTOS_DIR"/*; do
  [ -f "$f" ] || continue
  base=$(basename "$f")
  case "$base" in
    README.md|journey-manifest.js) continue ;;
  esac
  ext_lower=$(echo "${base##*.}" | tr '[:upper:]' '[:lower:]')
  case "$ext_lower" in
    jpg|jpeg|png|heic|webp)
      mv "$f" "$JOURNEY_DIR/$base"
      moved=$((moved + 1))
      ;;
    mp4|mov|m4v)
      # Live Photo / video sidecars — skip silently
      ;;
  esac
done
if [ "$moved" -gt 0 ]; then
  echo "Moved $moved image(s) into $JOURNEY_DIR/"
fi

# 2. Convert HEIC → JPG (browsers can't display HEIC).
#    Preserve the original file's modification time on the converted file so
#    chronological ordering stays consistent even if EXIF is missing later.
heic_files=$(find "$JOURNEY_DIR" -maxdepth 1 -type f \( -iname "*.heic" \) || true)
heic_count=$(echo "$heic_files" | grep -c . || true)
if [ "$heic_count" -gt 0 ] && [ -n "$heic_files" ]; then
  if command -v sips >/dev/null 2>&1; then
    echo "Converting $heic_count HEIC file(s) to JPG…"
    echo "$heic_files" | while read -r heic; do
      [ -z "$heic" ] && continue
      jpg="${heic%.*}.jpg"
      if [ ! -f "$jpg" ]; then
        sips -s format jpeg "$heic" --out "$jpg" >/dev/null
        touch -r "$heic" "$jpg"
      fi
      rm "$heic"
    done
    echo "  done."
  else
    echo "⚠ Found HEIC files but \`sips\` isn't available — convert them manually first."
  fi
fi

# 3. Build the manifest. Use sips's EXIF creation date when available;
#    fall back to filename pattern (YYYYMMDD), then mtime.
python3 - "$JOURNEY_DIR" "$OUT" <<'PY'
import os
import sys
import re
import subprocess
from pathlib import Path
from datetime import datetime

journey_dir = Path(sys.argv[1])
out_path    = Path(sys.argv[2])

EXTS = {'.jpg', '.jpeg', '.png', '.webp'}

FNAME_PATTERNS = [
    re.compile(r'(\d{4})[-_](\d{2})[-_](\d{2})'),
    re.compile(r'(\d{4})(\d{2})(\d{2})'),
]

def filename_date(name):
    for pat in FNAME_PATTERNS:
        m = pat.search(name)
        if m:
            y, mo, _ = m.groups()
            try:
                y_i, mo_i = int(y), int(mo)
                if 1990 <= y_i <= 2100 and 1 <= mo_i <= 12:
                    return f"{y_i:04d}-{mo_i:02d}", datetime(y_i, mo_i, 1).timestamp()
            except ValueError:
                pass
    return None

def sips_creation(path):
    """Read EXIF creation date via macOS's sips. Returns (yyyy-mm, unix_ts) or None."""
    try:
        out = subprocess.check_output(
            ['sips', '-g', 'creation', str(path)],
            stderr=subprocess.DEVNULL,
            timeout=4,
        ).decode('utf-8', errors='ignore')
    except Exception:
        return None
    m = re.search(r'creation:\s*(\d{4}):(\d{2}):(\d{2})\s+(\d{2}):(\d{2}):(\d{2})', out)
    if not m:
        return None
    y, mo, d, hh, mm, ss = m.groups()
    try:
        dt = datetime(int(y), int(mo), int(d), int(hh), int(mm), int(ss))
        return f"{int(y):04d}-{int(mo):02d}", dt.timestamp()
    except ValueError:
        return None

photos = []
for entry in sorted(journey_dir.iterdir()):
    if not entry.is_file():
        continue
    if entry.suffix.lower() not in EXTS:
        continue

    date_str = None
    sort_ts  = None

    # 1) sips EXIF
    sips_res = sips_creation(entry)
    if sips_res:
        date_str, sort_ts = sips_res

    # 2) filename pattern
    if date_str is None:
        fname_res = filename_date(entry.name)
        if fname_res:
            date_str, sort_ts = fname_res

    # 3) mtime fallback
    if date_str is None:
        mtime = datetime.fromtimestamp(entry.stat().st_mtime)
        date_str = mtime.strftime('%Y-%m')
        sort_ts  = entry.stat().st_mtime

    photos.append({
        'src': f"photos/journey/{entry.name}",
        'date': date_str,
        '_sort': sort_ts,
    })

photos.sort(key=lambda p: p['_sort'])
for p in photos: p.pop('_sort', None)

lines = ['// Auto-generated by scan-photos.sh — do not edit by hand.',
         '// Re-run `./scan-photos.sh` whenever you add or remove photos.',
         'window.JOURNEY_PHOTOS = [']
for p in photos:
    src = p['src'].replace("'", "\\'")
    lines.append(f"  {{ src: '{src}', date: '{p['date']}' }},")
lines.append(']')
lines[-1] = '];'

out_path.write_text('\n'.join(lines) + '\n')
print(f"✓ Wrote {len(photos)} photos to {out_path}")
if photos:
    print(f"  Earliest: {photos[0]['date']}   Latest: {photos[-1]['date']}")
PY
